// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAVLFhaLNGi1RJILtkK7n7t4rpmrM1HeE',
    appId: '1:677037114860:web:77c21bdce16004fa586cc9',
    messagingSenderId: '677037114860',
    projectId: 'tripsplit-3de4d',
    authDomain: 'tripsplit-3de4d.firebaseapp.com',
    storageBucket: 'tripsplit-3de4d.appspot.com',
    measurementId: 'G-EB6QW0K4P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl-8Zp7e11msg5VeAnotV-8PWlJB99xHI',
    appId: '1:677037114860:android:25fbee5c126e1748586cc9',
    messagingSenderId: '677037114860',
    projectId: 'tripsplit-3de4d',
    storageBucket: 'tripsplit-3de4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU4jl2NntU2sHvmbn9nRZKFSB__8747ZI',
    appId: '1:677037114860:ios:934366e65af326e9586cc9',
    messagingSenderId: '677037114860',
    projectId: 'tripsplit-3de4d',
    storageBucket: 'tripsplit-3de4d.appspot.com',
    iosBundleId: 'com.jayg.tripsplit',
  );

}